baseURL: https://huangjunye.github.io/
languageCode: en-us
title: Junye Huang
theme: "PaperMod"

params:
  defaultTheme: auto
  ShowCodeCopyButtons: true
  profileMode:
    enabled: true
    subtitle: Quantum Developer Advocate, IBM Quantum
    imageUrl: https://avatars.githubusercontent.com/u/7631333?v=4
  
  socialIcons:
    - name: KoFi
      url: https://ko-fi.com/junye
    - name: github
      url: https://github.com/HuangJunye
    - name: twitter
      url: https://twitter.com/HuangJunye
    - name: linkedin
      url: https://www.linkedin.com/in/huangjunye/
    - name: slack
      url: https://qiskit.slack.com/team/UG1GZP8PL
    - name: stackoverflow
      url: https://quantumcomputing.stackexchange.com/users/7474/junye-huang
    - name: email
      url: mailto:h.jun.ye@gmail.com

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: about
          url: about
          weight: 5
        - name: blog
          url: blog
          weight: 10
        - name: projects
          url: projects
          weight: 15
        - name: talks
          url: talks
          weight: 20

